# Generated by Django 2.2.1 on 2019-12-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_lineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pdf_report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
