# Generated by Django 2.2.1 on 2019-12-28 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_order_pdf_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pdf_report',
            new_name='Ivoice_pdf',
        ),
    ]
