# Generated by Django 2.2.1 on 2019-12-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_auto_20191228_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='city',
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='-', max_length=191),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='-', max_length=191),
            preserve_default=False,
        ),
    ]
