# Generated by Django 2.2.1 on 2019-08-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_pic', models.ImageField(upload_to='')),
                ('product_info', models.TextField()),
                ('product_price', models.CharField(max_length=50)),
            ],
        ),
    ]
