# Generated by Django 2.2.1 on 2019-09-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20190904_0816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='ProductDB',
        ),
    ]
