# Generated by Django 2.2.1 on 2019-09-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20190904_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='product_pic',
            field=models.ImageField(upload_to='Products/static'),
        ),
    ]
