# Generated by Django 2.2.1 on 2019-09-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20190906_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='product_pic',
            field=models.ImageField(upload_to='Products/media'),
        ),
    ]
