# Generated by Django 2.2.1 on 2019-12-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20190906_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200, unique=True)),
        ),
    ]
