# Generated by Django 2.2.1 on 2019-12-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_productdb_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='slug',
            field=models.SlugField(blank=True, default=None),
        ),
    ]
