# Generated by Django 2.2.1 on 2019-12-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_auto_20191208_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
